version: '3'
services:
  app:
    build: ./app
    ports:
      - '80:80'
    depends_on:
      - api
    volumes:
      - ./app/public:/usr/share/nginx/html
      
  api:
    build: ./api
    ports:
      - '8080:8080'
    env_file: .env
    environment:
      - MONGO_URL=$MONGO_URL
